/**
 * AUTO-GENERATED FILE — DO NOT EDIT BY HAND
 * Generated by: scripts/generate-form-api-access-map.mjs
 *
 * Placeholder committed by Module 13.
 * Run: node scripts/generate-form-api-access-map.mjs --write
 */
export const FORM_API_ACCESS_MAP: Record<string, string> = {
  "/api/forms/audit": "/dashboard/audit",
  "/api/forms/call-time": "/dashboard/data-entry/call-time",
  "/api/forms/decisions": "/dashboard/data-entry/decisions",
  "/api/forms/risks": "/dashboard/data-entry/risks"
};

export function dashboardRouteForApiPath(apiPath: string): string | null {
  return FORM_API_ACCESS_MAP[apiPath] ?? null;
}
